//////////////////////////////////////////////////////////////////////////////
//
// WordTsar - Wordstar clone for modern systems http://wordtsar.ca
// Copyright (C) 2018 Gerald Brandt
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//////////////////////////////////////////////////////////////////////////////

/**
 * @class cTUIDebugReport
 *
 * @brief TUI crash debug report generator and system information collector.
 *
 * Qt-free equivalent of the GUI cDebugReport class. Gathers system
 * information via POSIX uname(), locates crash data (core dumps and
 * backtraces), and packages everything into a timestamped ZIP file
 * for bug report submission.
 *
 * @section tui_debugreport_collection Data Collection
 * - System information: CPU architecture, kernel version, OS name
 *   (via POSIX uname() instead of Qt QSysInfo)
 * - Core dump files: searches standard locations and systemd-coredumpctl
 *   on Linux for the most recent crash dump
 * - Backtrace extraction: searches for backtrace files generated by chillout
 *
 * @section tui_debugreport_packaging Report Packaging
 * All collected data is written into a timestamped ZIP archive containing:
 * - debug_report.txt: hardware and OS details
 * - backtrace file (if found)
 * - core dump file (if found)
 *
 * @section tui_debugreport_output Output
 * Since no interactive dialog is available during a terminal crash,
 * all crash information is written to stderr and packaged into a ZIP
 * file. The user is instructed to email the ZIP to the developer.
 *
 * @author Gerald Brandt
 * @copyright GNU Affero General Public License v3.0
 *
 * @see cTUIDebugReport
 */

#include <iostream>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <iomanip>
#include <sstream>
#include <cstdlib>

#ifdef _WIN32
#include <direct.h>
#else
#include <unistd.h>
#include <sys/utsname.h>
#endif

#include "debugreport.h"

#define MINIZ_HEADER_FILE_ONLY 1
#include "zip.h"


/////////////////////////////////////////////////////////////////////////////
///
/// @return nothing
///
/// @brief
/// Constructor. Collects system information at construction time so
/// it is available if a crash occurs later.
///
/////////////////////////////////////////////////////////////////////////////
cTUIDebugReport::cTUIDebugReport(void)
{
    GetSystemInfo();
}


/////////////////////////////////////////////////////////////////////////////
///
/// @return nothing
///
/// @brief
/// Destructor.
///
/////////////////////////////////////////////////////////////////////////////
cTUIDebugReport::~cTUIDebugReport(void)
{
}


/////////////////////////////////////////////////////////////////////////////
///
/// @param  name [in] the executable name or path (typically argv[0])
///
/// @return nothing
///
/// @brief
/// Extract the application name from the executable path and store
/// the current working directory. The name is used to locate core
/// dump files (systemd strips everything after the first dot).
///
/////////////////////////////////////////////////////////////////////////////
void cTUIDebugReport::SetName(std::string name)
{
    std::filesystem::path filePath(name);
    mName = filePath.filename().string();

    // systemd drops everything after the first '.' in the core dump filename
#ifdef __linux__
    if (mName.find('.') != std::string::npos)
    {
        mName = mName.substr(0, mName.find('.'));
    }
#endif

    char *cwd = getcwd(NULL, 0);
    if (cwd != nullptr)
    {
        mPath = cwd;
        mPath += "/";
        free(cwd);
    }
    else
    {
        mPath = "./";
    }
}


/////////////////////////////////////////////////////////////////////////////
///
/// @return nothing
///
/// @brief
/// No-op in TUI context. The GUI version shows a Qt dialog for user
/// notes, but during a terminal crash we cannot safely display an
/// interactive dialog. Crash information goes to stderr and files.
///
/////////////////////////////////////////////////////////////////////////////
void cTUIDebugReport::Show(void)
{
    // No interactive dialog available during crash in terminal mode.
    // Crash info is written to stderr by the crash callback in main.cpp
    // and packaged by Coalesce().
}


/////////////////////////////////////////////////////////////////////////////
///
/// @return nothing
///
/// @brief
/// Collect all crash data and package into a timestamped ZIP file.
/// Writes a debug_report.txt with system info, finds core dump and
/// backtrace files, and creates a ZIP archive. Prints instructions
/// to stderr telling the user where to send the crash report.
///
/////////////////////////////////////////////////////////////////////////////
void cTUIDebugReport::Coalesce(void)
{
    // Find core dump and backtrace files
    std::string core;
    bool foundCore = FindCoreDump(mPath, core);

    std::string backtrace;
    bool foundBt = FindBacktrace(mPath, backtrace);

    // Write debug report text file with system info
    std::string dbgfile = mPath;
    dbgfile += "debug_report.txt";
    bool dbgWritten = false;
    std::ofstream outFile(dbgfile);
    if (outFile.is_open())
    {
        outFile << "Build CPU: " << mBuildCPU << "\n";
        outFile << "Current CPU: " << mCurrentCPU << "\n";
        outFile << "Kernel: " << mKernel << "\n";
        outFile << "Kernel Version: " << mKernelVersion << "\n";
        outFile << "Product: " << mPrettyProduct << "\n";
        outFile << "Core Dump File: " << core << "\n";
        outFile.close();
        dbgWritten = true;
    }
    else
    {
        std::cerr << "Unable to open file for writing debug report.\n";
    }

    // Build timestamped ZIP filename
    auto t = std::time(nullptr);
    auto tm = *std::localtime(&t);

    std::ostringstream oss;
    oss << "crashreport_" << std::put_time(&tm, "%Y%m%d_%H%M%S") << ".zip";
    std::string zipname = mPath + oss.str();

    // Only add files that were successfully created or found.
    // Passing a non-existent file to zip_create() causes it to fail
    // with ZIP_ENOFILE and abort the entire archive.
    const char *filenames[3];
    size_t filecount = 0;

    if (dbgWritten)
    {
        filenames[filecount++] = dbgfile.c_str();
    }
    if (foundCore)
    {
        filenames[filecount++] = core.c_str();
    }
    if (foundBt)
    {
        filenames[filecount++] = backtrace.c_str();
    }

    // Create the ZIP and check for errors
    if (filecount > 0)
    {
        int err = zip_create(zipname.c_str(), filenames, filecount);
        if (err != 0)
        {
            std::cerr << "Failed to create crash report ZIP (error " << err << ")\n"
                      << std::flush;
        }
        else
        {
            // Print instructions to stderr (terminal restored by crash callback)
            std::cerr << "\nA crash report has been created:\n"
                      << "  " << zipname << "\n\n"
                      << "The ZIP file contains:\n"
                      << "  - System information (CPU, OS, kernel version)\n"
                      << "  - A stack trace showing where the crash occurred\n";
            if (foundCore)
            {
                std::cerr << "  - A core dump file\n";
            }
            std::cerr << "\nNo personal information or document content is included.\n\n"
                      << "Please email this file to gbr@wordtsar.ca\n"
                      << "or attach it to a ticket at https://sourceforge.net/projects/wordtsar/\n"
                      << std::flush;
        }
    }
    else
    {
        std::cerr << "No crash report files available to package.\n" << std::flush;
    }
}


/////////////////////////////////////////////////////////////////////////////
///
/// @return nothing
///
/// @brief
/// Collect system information using POSIX uname(). Replaces the GUI
/// version which uses Qt QSysInfo. Stores kernel type, version,
/// CPU architecture, and OS product name.
///
/////////////////////////////////////////////////////////////////////////////
void cTUIDebugReport::GetSystemInfo(void)
{
#ifdef _WIN32
    mBuildCPU = "x86_64";
    mCurrentCPU = "x86_64";
    mKernel = "Windows";
    mKernelVersion = "unknown";
    mPrettyProduct = "Windows";
#else
    struct utsname info;
    if (uname(&info) == 0)
    {
        mKernel = info.sysname;
        mKernelVersion = info.release;
        mCurrentCPU = info.machine;
        mPrettyProduct = info.version;
    }

    // Build CPU from compile-time macro
#if defined(__x86_64__)
    mBuildCPU = "x86_64";
#elif defined(__aarch64__)
    mBuildCPU = "aarch64";
#elif defined(__i386__)
    mBuildCPU = "i386";
#elif defined(__arm__)
    mBuildCPU = "arm";
#else
    mBuildCPU = "unknown";
#endif

#endif
}


/////////////////////////////////////////////////////////////////////////////
///
/// @param  dir [in] directory to search for core dump files
/// @param  corefilename [out] path to the newest core dump file found
///
/// @return true if a core dump was found, false otherwise
///
/// @brief
/// Search for the most recent core dump file. On Linux, reads
/// /proc/sys/kernel/core_pattern to determine if systemd manages
/// core dumps (piped to a handler) or if they are written to the
/// current directory. Searches the appropriate location for files
/// matching the application name.
///
/////////////////////////////////////////////////////////////////////////////
bool cTUIDebugReport::FindCoreDump(std::string &dir, std::string &corefilename)
{
#ifdef __linux__
    bool coresystemd = false;
    std::string corelocation;

    // Check if systemd manages core dumps or if they go to CWD
    std::ifstream corePatternFile("/proc/sys/kernel/core_pattern");
    if (corePatternFile)
    {
        std::string corePattern;
        std::getline(corePatternFile, corePattern);
        corePatternFile.close();

        if (corePattern[0] == '|')
        {
            coresystemd = true;
            corelocation = "/var/lib/systemd/coredump/";
        }
        else
        {
            corelocation = dir;
        }
    }

    // Search the core dump directory for matching files
    std::filesystem::path dirPath(corelocation);

    if (!std::filesystem::exists(dirPath) || !std::filesystem::is_directory(dirPath))
    {
        std::cerr << "Error: " << dirPath << " is not a valid directory.\n";
        return false;
    }

    std::filesystem::path newestFile;
    std::chrono::system_clock::time_point newestTime;
    bool found = false;

    // Iterate over directory entries looking for the newest matching file
    for (const auto& entry : std::filesystem::directory_iterator(dirPath))
    {
        if (!entry.is_regular_file())
        {
            continue;
        }

        // Filter by application name (systemd) or "core" (traditional)
        std::string filename = entry.path().filename().string();
        if (coresystemd)
        {
            if (filename.find(mName) == std::string::npos)
            {
                continue;
            }
        }
        else
        {
            if (filename.find("core") == std::string::npos)
            {
                continue;
            }
        }

        // Track the newest file by modification time
        auto ftime = std::filesystem::last_write_time(entry);
        auto sctp = decltype(ftime)::clock::to_sys(ftime);

        if (!found || sctp > newestTime)
        {
            newestTime = sctp;
            newestFile = entry.path();
            found = true;
        }
    }

    if (found)
    {
        corefilename = newestFile;
        return true;
    }
    else
    {
        return false;
    }
#endif
    return false;
}


/////////////////////////////////////////////////////////////////////////////
///
/// @param  dir [in] directory to search for backtrace files
/// @param  btfilename [out] path to the newest backtrace file found
///
/// @return true if a backtrace file was found, false otherwise
///
/// @brief
/// Search for the most recent backtrace file in the given directory.
/// Backtrace files are identified by containing "bktr" in their
/// filename (generated by the chillout crash handler).
///
/////////////////////////////////////////////////////////////////////////////
bool cTUIDebugReport::FindBacktrace(std::string &dir, std::string &btfilename)
{
#ifdef __linux__

    std::filesystem::path newestFile;
    std::chrono::system_clock::time_point newestTime;
    bool found = false;

    // Iterate over directory entries looking for backtrace files
    for (const auto& entry : std::filesystem::directory_iterator(dir))
    {
        if (!entry.is_regular_file())
        {
            continue;
        }

        // Filter by "bktr" in filename (chillout backtrace naming convention)
        std::string filename = entry.path().filename().string();
        if (filename.find("bktr") == std::string::npos)
        {
            continue;
        }

        // Track the newest file by modification time
        auto ftime = std::filesystem::last_write_time(entry);
        auto sctp = decltype(ftime)::clock::to_sys(ftime);

        if (!found || sctp > newestTime)
        {
            newestTime = sctp;
            newestFile = entry.path();
            found = true;
        }
    }

    if (found)
    {
        btfilename = newestFile;
        return true;
    }
    else
    {
        return false;
    }
#endif
    return false;
}
